spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_sv_db?createDatabaseIfNotExist=true
    username: {DB_USERNAME}
    password: {DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true